# 베이스 이미지
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Playwright 설치
RUN pip install playwright && playwright install --with-deps

# 애플리케이션 코드 복사
COPY . .

# WSGI 서버 설치
RUN pip install gunicorn

# 환경 변수 설정
ENV FLASK_ENV=production
ENV FLASK_APP=run.py

# Gunicorn을 사용한 서버 실행
CMD ["gunicorn", "--config", "gunicorn.conf.py", "run:app"]