version: "3"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    command: npx nodemon --exec npx ts-node src/index.ts
